# Generated by Django 3.2 on 2022-04-16 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 21, 57, 49, 266527)),
        ),
    ]
