# Generated by Django 3.2.13 on 2022-04-15 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_newuser_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 0, 42, 11, 982466)),
        ),
    ]
